### ISSUE TITLE
Talos Deployment with Private Network Fails

### ISSUE THREAD

**Issue by xriser** [hcloud-k8s/terraform-hcloud-kubernetes#45]
Problem Description

Deploying Talos with a private network configuration is failing due to several issues observed during deployment:
	1.	Default Gateway Issue:
	•	The default gateway(10.4.0.1) is not applied to the nodes, resulting in no internet access.
	•	Without internet connectivity, the node is unable to boot fully.
	2.	Local Execution Network Conflict:
	•	When deploying from a network different from the Talos private network, local-exec operations fail.
	•	This happens because 10.4.64.1 (the control plane IP) is inaccessible outside the private network.
	3.	IP Assignment Instability:
	•	When deploying from the same network, the control plane receives IP address 10.4.64.1 temporarily.
	•	However, the IP address disappears shortly afterward, halting further deployment progress.
	•	This behavior was observed via the control plane console.

Configuration Details

Below is the latest configuration used during the deployment attempt:
```
module "kubernetes" {
  source  = "hcloud-k8s/kubernetes/hcloud"
  version = "0.12.0"

  cluster_name = "k8s"
  hcloud_token = var.hcloud_token

  cluster_kubeconfig_path  = "kubeconfig"
  cluster_talosconfig_path = "talosconfig"
  cluster_healthcheck_enabled = false

  network_ipv4_cidr         = "10.4.0.0/16"
  hcloud_network_id         = hcloud_network.k8s.id
  talos_ipv6_enabled        = false
  talos_public_ipv6_enabled = false
  talos_nameservers         = ["185.12.64.1", "185.12.64.2"]
  talos_version = "1.9.1"

  talos_sysctls_extra_args = {
    "net.core.rmem_default" = "26214400"
    "net.core.wmem_default" = "26214400"
    "net.core.rmem_max"     = "26214400"
    "net.core.wmem_max"     = "26214400"
    "vm.max_map_count"      = "262144"
  }

  kubernetes_version = "1.32.0"

  kubernetes_kubelet_extra_args = {
    system-reserved            = "cpu=100m,memory=250Mi,ephemeral-storage=1Gi"
    kube-reserved              = "cpu=100m,memory=200Mi,ephemeral-storage=1Gi"
    eviction-hard              = "memory.available<100Mi,nodefs.available<10%"
    eviction-soft              = "memory.available<200Mi,nodefs.available<15%"
    eviction-soft-grace-period = "memory.available=2m30s,nodefs.available=4m"
  }

  cluster_access = "private"
  talos_public_ipv4_enabled = false
  cluster_delete_protection = false

  kube_api_load_balancer_enabled = true
  hcloud_load_balancer_location = "fsn1"
  kube_api_load_balancer_public_network_enabled = true

  cert_manager_enabled  = false
  ingress_nginx_enabled = false

  control_plane_nodepools = [
    { name = "control", type = "cx22", location = "fsn1", count = 1 }
  ]
  worker_nodepools = [
    { name = "worker", type = "cpx41", location = "fsn1", count = 1 }
  ]
}
```

**Comment by M4t7e** [comment]
You set `cluster_access = "private"`, which means, that you somehow have access to the internal Hetzner network. How do you access the cluster network from the machine where this module is being executed?

> The default gateway(10.4.0.1) is not applied to the nodes, resulting in no internet access.

`10.4.0.1` is not supposed to be a default gateway, nor can it provide access to the internet by default. If you have a router / NAT-GW in your network and added a (default) route in the Hetzner Network to that machine, you still need to configure all Talos nodes so that they route more than the Hetzner Network CIDR (`10.4.0.0/16` in your case) to the Hetzner Router with `talos_extra_routes`.

> Without internet connectivity, the node is unable to boot fully.

This is an expected behavior. See https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/issues/42#issuecomment-2567121209 for the reason.


Please also see the [Cluster Access](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes#hammer_and_pick-advanced-configuration) chapter for more infos regarding the different cluster access options.

**Comment by xriser** [comment]
Yes, I’m working on building a fully private Kubernetes cluster using best security practices and adhering to the “least privilege” principle.

To achieve this, a NAT gateway is essential. Hetzner provides clear instructions on setting up a NAT gateway and connecting it to a private network: [Hetzner NAT Gateway Setup](https://community.hetzner.com/tutorials/how-to-set-up-nat-for-cloud-networks).

In my case, the network is 10.4.0.0/16, and Hetzner automatically assigns the first address, 10.4.0.1, as the gateway for the network. My NAT gateway host is 10.4.0.2. To enable internet access for the private nodes, I simply added a default route (0.0.0.0/0 via 10.4.0.2) in the Hetzner network routes tab. The nodes themselves must have a default route pointing to 10.4.0.1.

To configure this for Talos, I need the ability to add a default gateway in the Talos node configuration. Specifically, the routes section in the Talos network config: [Talos Network Configuration](https://www.talos.dev/v1.4/reference/configuration/#networkconfig). I would add a route for 0.0.0.0/0 via 10.4.0.1.

With this setup, nodes only have private IPs and can access the internet for outbound traffic. This aligns with the standard private Kubernetes cluster architecture. Public cloud providers like GCP and AWS offer managed NAT services like Cloud NAT or Cloud Router, but in Hetzner, you need to manually build and configure the NAT machine.

This approach eliminates the need for public IPs and additional firewall rules, which are both unnecessary overhead and a potential security risk.

Additionally, I understand the need for direct access to Talos nodes due to the local-exec commands used in Terraform. To address this, I’ve been running Terraform directly from the NAT gateway and added a couple of static routes to the Talos control plane and worker nodes:
`ip r add 10.4.64.0/24 via 10.4.0.1 dev enp7s0 onlink  
ip r add 10.4.65.0/24 via 10.4.0.1 dev enp7s0 onlink  `
I verified connectivity by pinging the nodes and accessing the API ports via the internal network.
Everything works as expected when cluster_access = "public" and the nodes are fully up. However, once I set cluster_access = "private", the nodes fail to boot fully. I believe this is due to the lack of a proper default gateway (10.4.0.1) in private mode, preventing the nodes from accessing the internet to pull necessary resources.

**Comment by xriser** [comment]
I've managed to run control plane with private IP only
<img width="1293" alt="Screenshot 2025-01-02 at 18 31 39" src="https://github.com/user-attachments/assets/51937bdb-1654-4760-aa22-9143185f1621" />
To make this happen I am hardcoded network section https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/blob/main/talos_config.tf#L120 like this 
 
`network = {
          interfaces = [
            {
              interface = "eth0"
              dhcp      = true
              dhcpOptions = {
                ipv6 = false
              }
              routes = [
                {
                  network = "0.0.0.0/0"
                  gateway = "10.4.0.1"
                }
              ]
            }
          ]
          nameservers      = var.talos_nameservers
          extraHostEntries = local.extra_host_entries
        }`
        
I addressed the issue by adding the default gateway manually like this.

Looking at your network configuration, it seems there are always two interfaces present. This might be causing problems when I try to set up private networking only. In this case, eth0 appears reserved for a public IP, even though no public IP is assigned, while eth1 is supposed to handle the private IP. However, this setup doesn’t seem to work correctly.

There’s really no need for two interfaces in a private-only configuration. A single eth0 with a private IP and the correct default gateway should be sufficient.

I understand this would add complexity to the logic for handling different cases—like public + private, public-only, private-only, or VIPs—but it seems like the only way to make private mode work reliably.

**Comment by M4t7e** [comment]
Okay, I understand. I never tried this kind of setup myself. As previously mentioned, you need to manually add the route to your configuration using `talos_extra_routes`. There is no automated way from Hetzner to provision your manually added network routes to the nodes.

**Example:**
```hcl
talos_extra_routes = ["0.0.0.0/0"]
```
This will add `0.0.0.0/0` as a route to the Talos nodes with the Hetzner network router (`10.4.0.1`) as gateway. The Hetzner router will use your manually added network default route and forward it to `10.4.0.2`, if the destination is not within the internal network.

The traffic should flow like this: `node` -> `10.4.0.1` -> `10.4.0.2` -> `internet`

> To address this, I’ve been running Terraform directly from the NAT gateway and added a couple of static routes to the Talos control plane and worker nodes

Normally this should not be necessary when your NAT-GW is in the same network. It should learn the route to the internal network via DHCP.

**Comment by xriser** [comment]
Hey, I’m glad you understand what I’m trying to achieve!

I tried adding this option:
`talos_extra_routes = ["0.0.0.0/0"]`
but it didn’t work. I’ll give it another shot and let you know the results.

From what I’ve observed, the issue is likely because the route is being added via the second interface, eth1, while eth0 remains unconfigured. Could this be the cause?

**Comment by M4t7e** [comment]
It could be a DHCP config on eth0 that still sets a default route there. If you have the chance to check `talosctl get routes`, when both network interfaces are configured together with `talos_extra_routes = ["0.0.0.0/0"]`, we should see what is going on.

You can also try to set `talos_extra_routes = ["0.0.0.0/1", "128.0.0.0/1"]` as these are a "better" (more specific) routes than `0.0.0.0/0`.

**Comment by xriser** [comment]
`talos_extra_routes = ["0.0.0.0/0"]`
doesn't work
`talos_extra_routes = ["0.0.0.0/1", "128.0.0.0/1"]`
doesn't work

I’m having trouble figuring out what’s happening because Talos seems to be removing the IP address for some reason. It initially assigns 10.4.64.1, but after a few seconds, it gets removed.

<img width="1535" alt="Screenshot 2025-01-02 at 19 42 45" src="https://github.com/user-attachments/assets/3f71b2d2-5dcc-4d30-a7a0-2ddcdd4bfc7f" />
<img width="1535" alt="Screenshot 2025-01-02 at 19 44 36" src="https://github.com/user-attachments/assets/20787fed-09c6-4cc4-8c30-6aaf78e2b33f" />



https://drive.google.com/file/d/10nSV7LrsMjM9PGbazEuRd5m5J7mGX_OV/view?usp=sharing

**Comment by M4t7e** [comment]
It appears that the public network interface ceases to exist when public IPv4 and IPv6 networks are disabled, leading the internal network interface to be recognized as `eth0` instead of `eth1`. This issue is solved in [0.12.2](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/releases/tag/0.12.2)

**Comment by xriser** [comment]
Still doesn't work.
The control-plane IP doesn't disappear anymore, but the GW is empty. (see screenshot)
<img width="1117" alt="Screenshot 2025-01-03 at 20 48 13" src="https://github.com/user-attachments/assets/0ee80767-081c-4f9f-b8c0-dc20b0167dfc" />

Now I have access to the cluster and here is `talosctl get routes output`

<img width="1239" alt="Screenshot 2025-01-03 at 20 49 41" src="https://github.com/user-attachments/assets/73b7090d-0a59-46cd-8fb9-0aa7b6df600a" />

talos_extra_routes here is:
talos_extra_routes = ["0.0.0.0/1", "128.0.0.0/1"]

**Comment by xriser** [comment]
I've applied talos_extra_routes = ["0.0.0.0/0"]
Now it seems to work 
<img width="1093" alt="Screenshot 2025-01-03 at 20 56 33" src="https://github.com/user-attachments/assets/fe4b29a6-1295-4578-a4a3-8e20f88a5bf6" />

<img width="1310" alt="Screenshot 2025-01-03 at 20 56 51" src="https://github.com/user-attachments/assets/c767c077-e08b-43f0-b82b-39345e3b110c" />
